R/posterior-package.R
R/print.R
man-roxygen/args-print-max_chains.R
man-roxygen/args-print-max_draws.R
man-roxygen/args-print-max_iterations.R
man-roxygen/args-print-max_variables.R
man/posterior-package.Rd
man/print.draws_array.Rd
man/print.draws_df.Rd
man/print.draws_list.Rd
man/print.draws_matrix.Rd

This prefixes global options with `"posterior."` and documents them in `posterior-package`. Closes #82.

standardize and document global option names, closes #82

---

R/convergence.R

This PR fixes the reference.
This came up in https://github.com/arviz-devs/arviz/pull/1366#discussion_r479935719
Thanks @avehtari for the correction.

Fix Blom 1958 reference

---

R/as_draws_array.R

When we use as_draws_array and we only have 1 chain we could optimize the function a bit. 
Testing scenario: 
```r
library(cmdstanr)
model_code <- "
parameters {
real k;
}
transformed parameters {
real x[50000] = rep_array(k, 50000);
}
model {
k ~ normal(0, 1);
}
"
model_file <- write_stan_file(model_code)
mod <- cmdstan_model(model_file)
fit <- mod$sample(iter_sampling = 2000, validate_csv = FALSE, chains = 1)
data <- data.table::fread(cmd= paste0("grep -v '^#' ", fit$output_files()[1]))
times <- c()
for (i in 1:10) {
start <- Sys.time()
d_a <- posterior::as_draws_array(data)
times <- c(times, as.double((Sys.time()-start), units = "secs"))
}
print(times)
```
this branch:
```
1.838615 1.740373 1.687281 1.830399 1.704403 1.841837 1.646028 1.733209 1.632276 1.731928
```
mean 1.74s
master: …

Special case as_draws_array for length 1

---

R/as_draws_array.R
R/as_draws_matrix.R
tests/testthat/test-draws-index.R

Allows drop=TRUE when indexing draws_array objects as discussed in https://github.com/stan-dev/loo/pull/161.

allow drop=TRUE for draws_array

---

R/as_draws_df.R
tests/testthat/test-as_draws.R

`draws_df()` currently munges syntactically invalid names via a call down to `as.data.frame()` in a way that makes usage with indexed variables annoying:
```r
> draws_df(`x[1]` = 1:2, `x[2]` = 3:4)
x.1. x.2.
1    1    3
2    2    4
```
This PR fixes it:
```r
> draws_df(`x[1]` = 1:2, `x[2]` = 3:4)
x[1] x[2]
1    1    3
2    2    4
```

Don't munge names in draws_df

---

R/draws-index.R
tests/testthat/test-subset_draws.R

Addresses #129.
Makes `check_existing_variables()`, and therefore `subset_draws()` much more efficient. For example, with default arguments, this suggested version can process 300k variables in a fraction of a second while the current version takes almost 10 minutes. However, both versions still have comparable runtimes when  `regex = TRUE`.
```
x <- as_draws_matrix(matrix(rnorm(10 * 300000), nrow = 10, ncol = 300000))
microbenchmark::microbenchmark(
posterior:::check_existing_variables(variables = colnames(x), x = x),
posterior::subset_draws(x, variable = colnames(x)),
times = 10,
unit = "s"
)
Unit: seconds
min        lq      mean    median        uq       max neval
0.3240343 0.3354325 0.3669232 0.3541255 0.3870651 0.4765244    10
0.4236527 0.4271074 0.4862439 0.4566513 0.5303358 …
```

make subset_draws efficient

---

DESCRIPTION
R/as_draws_df.R
R/extract_variable_matrix.R
R/misc.R
R/rvar-.R
R/rvar-slice.R
R/summarise_draws.R

Fixes #135.
- With default dims = NULL, `drop_dims()` drops all single-level dimensions as expected
- `drop_dims()`'s output excludes the `draws_array` class and therefore doesn't use the `print.draws_array` method

updated drop_dims()

---

R/as_draws.R
R/as_draws_array.R
R/as_draws_df.R
R/as_draws_list.R
R/as_draws_rvars.R
R/bind_draws.R
R/convergence.R
R/draws-index.R
R/extract_variable.R
R/extract_variable_matrix.R
R/misc.R
R/mutate_variables.R
R/rename_variables.R
R/resample_draws.R
R/rstar.R
R/rvar-.R
R/rvar-dist.R
R/rvar-math.R
R/rvar-print.R
R/rvar-rfun.R
R/rvar-slice.R
R/subset_draws.R
R/summarise_draws.R
R/thin_draws.R
R/weight_draws.R

I think it will make our source code easier to read if function names indicate their purpose as much as possible. Most of our function names already do this well, but this PR changes a few that don't: 
`deparse2` -> `deparse_pretty` 
`drop2` -> `drop_dims_or_classes`
`stop2` -> `stop_no_call` 
I'm not attached to these particular new names so I'm happy to change them if anyone has suggestions, but I think these names at least hint at the reason for the existence of the functions.

use more informative internal function names

---

R/as_draws_df.R
R/draws-index.R
R/repair_draws.R
tests/testthat/test-as_draws.R
tests/testthat/test-subset_draws.R

Fixes #134 and and speeds up `as_draws_df()`:
- makes the `as_draws_df` methods vectorized, faster and more concise
- resolves row name inconsistencies that occur after transformations from various classes to `draws_df`
- switches to invisible returns for `check_*_*()` functions to prevent their output from getting printed
- enforces equal input lengths in `compute_draw_ids()` to avoid incorrect outputs due to recycling of vector elements
- applies more strict tests in relevant parts

Updated as_draws_df()

---

R/summarise_draws.R
tests/testthat/test-summarise_draws.R

This can close https://github.com/stan-dev/posterior/issues/98.
`summarise_draws` now internally writes output to a preallocated matrix, which makes the "chunking" option unnecessary except for parallelization, which will be dealt with separately.  
Additionally, we now check whether
```
if ("variable" %in% the_names) {
stop2("Name 'variable' is reserved in 'summarise_draws'.")
}
```
prior to the potentially lengthy computation.
Benchmarks are:
```
remotes::install_github("jsocolar/posterior")
library(posterior)
library(microbenchmark)
set.seed(1)
nc <- 4
n <- 100
test_array <- array(data = rnorm(1000*nc*n), dim = c(1000,nc,n))
y <- posterior::as_draws_array(test_array)
b100 <- microbenchmark(m_s <- posterior::summarise_draws(y), times = 10)
n <- 1000
test_array <- array(data = …
```

Improve summarise_draws efficiency

---

R/rstar.R
man/rstar.Rd

This changes the `rstar()` example from "dontrun" to "donttest", and also wraps it conditionally to run only if {caret} is installed (as {caret} is only in "Suggests"). For #165.

make rstar example "donttest" instead of "dontrun"

---

R/convergence.R
R/draws-index.R
R/rvar-.R
R/rvar-cast.R
man/diagnostics.Rd
man/draws-index.Rd
man/draws_of.Rd
man/quantile2.Rd
man/vctrs-compat.Rd

This PR adds `@return`s for functions docs mentioned in #165, with the exception of `reserved-variables`.

add @return for remaining doc pages except reserved-variables

---

R/rvar-math.R
tests/testthat/test-rvar-math.R

In base R bare vectors (without dims) are promoted to row/col vectors depending on if they are on the left or right side of `%*%`. e.g. this works:
```r
c(1.5, 3.5, 5.5) %*% c(7.5,  9.5, 11.5)
```
```
[,1]
[1,] 107.75
```
Currently this promotion works with rvars so long as both sides are rvars:
```r
x_array = array(1:6, dim = c(2,3))
x = new_rvar(x_array)
y_array = array(7:12, dim = c(2,3))
y = new_rvar(y_array)
x
```
```
rvar<2>[3] mean ± sd:
[1] 1.5 ± 0.71  3.5 ± 0.71  5.5 ± 0.71 
```
```r
y
```
```
rvar<2>[3] mean ± sd:
[1]  7.5 ± 0.71   9.5 ± 0.71  11.5 ± 0.71 
```
```r
x %**% y
```
```
rvar<2>[1,1] mean ± sd:
[,1]     
[1,] 108 ± 28 
```
But fails if one side is not an rvar:
```r
x %**% c(7.5,  9.5, 11.5)
```
```
Error: Second argument (`y`) is not a vector or matrix, cannot …
```

ensure base vectors are promoted to row/col vectors in rvar matrix mult

---

R/as_draws_rvars.R
R/draws-index.R
R/merge_chains.R
R/rvar-.R
R/rvar-cast.R
R/rvar-print.R
R/subset_draws.R
tests/testthat/test-rvar-.R
tests/testthat/test-rvar-math.R
tests/testthat/test-rvar-rfun.R
tests/testthat/test-rvar-slice.R

This is a stop-gap measure to improve performance on some operations when `rvar`s are used with `vctrs` functions, which generally comes up when `rvar`s are put into `tibble`s. It should not affect the output of any operations, just speed. No need to merge before CRAN if that ship has already sailed, but I figured I would submit this now since it gets it off my plate :).
For more info see r-lib/vctrs#1411
Basically: several `vctrs` functions call `vec_proxy()`, which must return a "proxy" for the vector as an "elementary" vector (some kind of object consisting of base lists, vectors, or data.frames) that can be sliced in a manner respecting the semantics of the object. Which in our case basically means returning a list indexed by the first index of the `rvar` (i.e. the second index of the …

cache vec_proxy results as stopgap for r-lib/vctrs#1411

---

README.Rmd
README.md
docs/articles/index.html
docs/articles/posterior.html
vignettes/posterior.Rmd

With the CRAN release now live, I removed posterior from the Stan r-packages. The command
```r
install.packages("posterior", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```
still works, but it does the same as regular install.packages. There is currently no reason to have posterior duplicated in our repository as well. It just duplicates work and will inevitably become out of sync. In the unlikely event we will need to host it again, we can simply add it back. Till then the CRAN + Github install will work just fine.
There was mention of the stan-dev/r-packages in a vignette as well.
- Code: BSD 3-clause …

Cleanup the mention of posterior on stan-dev/r-packages repo

---

R/rstar.R
tests/testthat.R
tests/testthat/test-rstar.R

I was thinking about the whole caret namespace thing (#164) and realized there's another way to solve it: to attach and detach caret just for the duration of the `rstar()` function if the user does not have it attached already. This PR implements that solution, which makes us no longer dependent on caret changing how it expects users to use it.

Manually attach/detach caret as needed for rstar

---

DESCRIPTION
NEWS.md
R/as_draws_rvars.R
tests/testthat/test-as_draws.R

This fixes #192 by falling back to the default list conversion behavior in as_draws_rvars.list() unless the input is a list of rvars.

allow as_draws_rvars to accept lists of lists, closes #192

---

R/convergence.R

Drop *fft_next_good_size()* function and replace its uses with *nextn()* from base R (*stats* package).
*nextn()* should be a lot faster and better handle corner cases.

Replace fft_next_good_size() by nextn()

---

NEWS.md
R/rvar-rfun.R
tests/testthat/test-rvar-rfun.R

This closes #195, which revealed that draws do not always line up properly between parameters in rvar_rng. One of those cases where what I had thought was a nice elegant solution failed in some (fairly important!) corner cases. This PR includes some better tests to cover those corner cases (and some that came up in the process of fixing this).
If anyone cares, in untangling the solution I basically realized that the draws dimension must be first prior to flattening the draws array and passing it to an rng functions in order for R vector recycling to work correctly (really I should have realized this before since I used this fact to implement array broadcasting for rvars in the first place). The upshot though is that some manual recycling must be done on non-rvar input.
Anyway the upshot …

fix some vector recycling issues with rvar_rng, closes #195

---

R/convergence.R

Fixes #198
If var(x)==0 ,the fix for #126 computed 0/0  and thus returned NA instead of 0 autocovariances.
This PR adds check for var(x)==0 in autocovariance function.

if variance is 0, return autocovariance 0

---

NEWS.md
R/draws-index.R
tests/testthat/test-subset_draws.R

This PR tries to fix #188. The basic approach I took here is to `grep` through the variable names. This is slow, and increases non-linearly in the number of variables, so probably isn't what you actually want to include. Hopefully the test cases are useful.
If you see a way to make this significantly faster, let me know!
I skipped the performance test for now. It takes 11s to run with 10,000 variables (the test requires 300,000 variables in less than a second).

Keep variable order in subset_draws()

---

DESCRIPTION
NEWS.md
R/bind_draws.R
tests/testthat/test-bind_draws.R

Fixes `bind_draws_df` which resulted wrong output for `.chains`, `.iter` and `.draw` columns when binding more than two objects. Earlier output:
```
set.seed(1)
x1d <- draws_df(alpha = 1:3, beta = rnorm(3))
x2d <- draws_df(alpha = 4:6, beta = rnorm(3))
x3d <- draws_df(alpha = 7:9, beta = rnorm(3))
x4d <- draws_df(alpha = 10:12, beta = rnorm(3))
x12d <- bind_draws(x1d, x2d, along = "chain")
d_df <- bind_draws(x12d, x3d, x4d, along = "chain")
print(d_df)
alpha  beta
1      1 -0.63
2      2  0.18
3      3 -0.84
4     NA    NA
5     NA    NA
6     NA    NA
7      4  1.60
8     10 -0.31
9      5  0.33
10    11  1.51
data.frame(d_df)
alpha       beta .chain .iteration .draw
1      1 -0.6264538      1          1     1
2      2  0.1836433      1          2     2
3      3 -0.8356286      1 …
```

Fix hidden variables in bind_draws_df when binding more than two objects

---

.github/workflows/rcmdcheck.yml

Upgrades to Ubuntu-1804 for testing. The 16.04 are now obsolete.

Update GHA Ubuntu instances

---

NEWS.md
R/print.R
tests/testthat/test-print.R

This fixes #217 
It also updates `NEWS.md` with a few entries for recent PRs of mine that I forgot to include previously ;)
Since we already discussed this fix at #217, once the checks pass I will merge this.

fix print.draws_df for objects with unrepaired draws

---

DESCRIPTION
NEWS.md
R/convergence.R
man-roxygen/ref-kenney-stats-1951.R
man/ess_sd.Rd
man/mcse_sd.Rd

PR for issue #232 better mcse_sd

better mcse_sd

---

R/convergence.R

mcse_sd was estimating ESS from abs(x-E[x]). In my old simulations, this had worked better than (x-E[x])^2. It's likely that the change in how the rest of MCSE for sd is estimated (PR #233) did affect that now the more logical (x-E[x])^2 works better, as demonstrated by simulations run by @sethaxen.
Here are the plots for the new simulation results

minor change in ESS estimation in mcse_sd based on more simulations

---

NEWS.md
R/as_draws_rvars.R
tests/testthat/test-as_draws.R

This closes #265 by ensuring that the dimensions of length-1 arrays in are preserved when converted to draws_rvars format. 
@wds15 can you verify this solves the problems you had in OncoBayes2? Thanks!

ensure as_draws_rvars preserves dims of length-1 arrays, closes #265

---

NEWS.md
R/rvar-.R
tests/testthat/test-rvar-.R
tests/testthat/test-rvar-cast.R

This PR closes #269 and #267 by removing `"list"` from the end of the class definition of `rvar`. This ensures that `vctrs::vec_is_list(<rvar>)` is `FALSE` (fixing some issues with dplyr, closing #269) and ensures that the S4 class definition of `"rvar"` does not redefine the S4 parent class of `"vctrs_vctr"` to be `"list"` (closing #267).
Since we already discussed this on #269, once the tests pass here I will merge.

Remove `"list"` from rvar class definition.

---

DESCRIPTION
NEWS.md
R/as_draws_df.R
R/rvar-.R
R/zzz.R
tests/testthat/test-rvar-.R

This is another minor fix related to #269, caught due to @bwiernik's due diligence. It ensures that `rvar`s with the new class definition can still be used in ggplot2.
Apologies for not including it in the earlier PR, I missed a bug in my testing. Once tests pass I will merge this.

One more minor fix for #269: define ggplot scale type for rvar

---

R/rvar-.R
R/rvar-factor.R
tests/testthat/test-rvar-factor.R
vignettes/rvar.Rmd

This is a fix for a minor issue with `rvar_factor()` I've run into after using a bit more in practice. 
Currently, given an array `x` with a `"levels"` attribute, `rvar(x)` will attempt to construct an `rvar_factor` instead of a numeric `rvar`. However, this can fail if `x` has more unique values than are in `"levels"` --- basically, if `"levels"` is not intended as a set of levels corresponding to integer entries of `x`. An example of such objects includes some output from `brms::posterior_predict()`, which makes `rvar(brms::posterior_predict())` fail in some cases (when it should really always work).
This PR is just a slight change: instead of automatically attempting to use the `"levels"` attribute in `rvar(x)`, this makes it so that the `"levels"` attribute is only examined if the …

Do not automatically create an rvar_factor when rvar() is passed a numeric array with levels

---

DESCRIPTION
NEWS.md
R/rvar-rfun.R
man/rfun.Rd
tests/testthat/test-rvar-rfun.R

This ensures rfun works with primitive functions (closes #290) and dots arguments (closes #291).

ensure rfun works with primitive functions and dots arguments

---

R/summarise_draws.R
tests/testthat/test-summarise_draws.R

This is a minor fix that perhaps I should have noticed and fixed with #275. When using `summarise_draws()` in Rmarkdown in RStudio, negative numbers get printed oddly, because the value of `print(summarise_draws())` (not just `summarise_draws()`) seems to be used under the hood to construct the table, and `print.draws_summary()` modifies column types. Note column `q5`:
The solution is to use `tibble:set_num_opts` instead of `tibble:num` in the printing code, as this adds an attribute with the formatting information to the column rather than changing it to a `pillar_num` object. Note that the column types above are also `pillar_num`, when they should be `dbl`.
This PR implements that simple fix. Output under this PR:
I don't think this really deserves a news entry since it's pretty minor …

Minor bugfix for use of summarise_draws in Rmarkdown

---

README.Rmd
README.md

Add examples of converting base R 3-D array and mcmc/mcmc.list objects
As it took me a moment to figure out how to convert R 3-D array to draws so that variables are named (as the approach used for matrix doesn't work) it is probably helpful for others to see the example, too.
I didn't even know that mcmc/mcmc.list object conversion is supported, and it would be useful to mention it at least once somewhere, so that it is possible to point others to tha information.

Add examples of converting base R 3-D array and mcmc/mcmc.list objects to README.md

---

NEWS.md
R/rvar-bind.R
R/rvar-math.R
R/rvar-slice.R
tests/testthat/test-rvar-slice.R

This is a handful of minor fixes for rvar on R 4.4, and closes #304. All of these fixes address slight changes in the handling of dimnames or function arguments in R 4.4 and have no meaningful impact on functionality.

CRAN test fixes for rvar on R 4.4

---

NEWS.md
R/bind_draws.R
R/order_draws.R
tests/testthat/test-bind_draws.R
tests/testthat/test-split_chains.R

This PR closes #300. The underlying issue in #300 is that `bind_draws(<draws_rvars>, along = "chain")` did not re-generate draw ids, so the resulting object from `split_chain(<draws_rvars>)` (which uses `bind_draws()` could have multiple draws with th same id.
Notably, this  bug might have been caught more easily if there was a warning issued by `order_draws(<rvar>)` if it needs to merge chains. I added a simple warning using `warn_merge_chains()`, but with the default settings that warning is not issued anyway. So I'm not sure if we want some other long-term solution, maybe warning levels or something?
- Code: BSD 3-clause …

Regenerate draw ids for bind_draws(<draws_rvar>, along = "chain")

---

R/draws-index.R
R/rename_variables.R

Cross-reference rename_variables and set_variables in See also sections
Please describe the purpose of the pull request. 
Aki Vehtari

Cross-reference rename_variables and set_variables

---

R/pareto_smooth.R
R/weight_draws.R

As stated in #329, testthat is currently an unlisted dependency due to `checkmate::expect_*` usage. This changes the code to `checkmate::assert_*` which was likely the original intention.

Replace checkmate::expect_* with checkmate::assert_* outside tests

---

R/pareto_smooth.R

This fixes an issue in pareto smoothing log weights as the `are_log_weights` argument was not properly passed through

fix to log weight smoothing

---

tests/testthat/test-pareto_smooth.R

Minor fix to test for log weight pareto smoothing

fix pareto smoothing weights test

---

R/pareto_smooth.R
tests/testthat/test-pareto_smooth.R

As brought up by @avehtari in issue #345, when one tail is constant, but `tail = "both"` is specified, it is better to return the diagnostic for the non-constant tail rather than `NA`.

Pareto k tail fix

---

man-roxygen/ref-vehtari-paretosmooth-2022.R

update psis ref journal info

---

R/rvar-.R

Adds assertions to prevent draws of invalid types being used in an rvar. Closes #363.

type check assertions for rvar draws, closes #363

---

R/pareto_smooth.R
man-roxygen/args-pareto.R
man/pareto_diags.Rd
man/pareto_khat.Rd
man/pareto_smooth.Rd

Sets `r_eff` back to `NULL` as default for `pareto_smooth`. At a later time, this may be changed, but now this fixes the inconsistency.
Fixes #368 

`r_eff` default to `NULL`

---

R/pareto_smooth.R

Improves checking for input for pareto diagnostic functions. Fixes issue #315 

Improve input checking and warnings for pareto diags

---

vignettes/pareto_diagnostics.Rmd
vignettes/posterior.Rmd

new Pareto-k diagnostics vignette

---

R/nested_rhat.R
man-roxygen/ref-margossian-nestedrhat-2024.R
man-roxygen/ref-vehtari-rhat-2021.R
man/ess_basic.Rd
man/ess_bulk.Rd
man/ess_quantile.Rd
man/ess_sd.Rd
man/ess_tail.Rd
man/mcse_quantile.Rd
man/mcse_sd.Rd
man/rhat.Rd
man/rhat_basic.Rd
man/rhat_nested.Rd

Adjust citation for nested R-hat to published version and fix references to parts of the paper. Also fixes a typo in the journal name for the rank normalized R-hat paper.

reference updates

---

R/convergence.R
man/ess_mean.Rd
man/ess_quantile.Rd

`ess_mean.default` was pointing to the ess_quantile documentation page, this fixes it to point to the `ess_mean` page

fix rdname for ess_mean

---

R/convergence.R
R/pareto_smooth.R
R/summarise_draws.R
tests/testthat/test-convergence.R
tests/testthat/test-pareto_smooth.R

Adds weighted ESS, MCSE and Pareto diagnostics.

Weighted diagnostics

---

R/pareto_smooth.R

Use of ceiling() for both conditions in ps_tail_length
Fixes #382 

fix use of ceiling in ps_tail_length

---

R/convergence.R
R/misc.R

closes #375
Fixes autocorrelation() function not printing its return value.  

fix autocorrelation() not printing

---

DESCRIPTION
NEWS.md
R/as_draws.R
R/as_draws_array.R
tests/testthat/test-as_draws.R

This PR allows to convert lists of matrices to `draws_array` objects. We had to initially revert as it was causing issues in cmdstanr models with one chain (#386). 
In this PR I also fix the issue with `as_array_matrix_list` such that we now should no longer see any issues. Interestingly, I believe that the bug in `as_array_matrix_list` existed also previously (for a long time I think). Just nobody used `as_array_matrix_list` until I made more objects to trigger it being called. Anyway it works now. 
@jgabry can you perhaps quickly check and confirm that it now works as expected? It passes all posterior and cmdstanr tests for me and works with one-chain models.
- …

 Convert lists of matrices to `draws_array` objects

---

R/convergence.R
tests/testthat/test-convergence.R

@sethaxen pointed out that PR #266 had made the change only in `mcse_sd()`, but based on the same justification, the change should have been made to `ess_sd()`, too. This makes the change for `ess_sd()` and updates the test value range for `ess_sd()`.

use the same equation in ess_sd as in mcse_sd

---

R/convergence.R

u_scale() function had quite old documentation text, and this PR fixes it to match with the actual implementation

fix documentation of u_scale()

---

R/pareto_smooth.R

This should fix #396 
@avehtari would you check that this is correct? There's also the question of whether to use floor (like the paper) or ceiling (like we have been using).

properly take into account r_eff when deciding tail length

---

_pkgdown.yml

closes #404, thanks to @ctholley
Fixes typo in _pkgdown.yml

Fix typo in _pkgdown.yml
